[package]
name = "hooks_server"
version = "0.1.0"
authors = ["Leonard Dahlmann <leo.dahlmann@gmail.com>"]

[dependencies]
hooks_common = { path = "../hooks_common" }
log = "0.4"
bit_manager = "*"
simple_logger = "0.3.1"
