[package]
name = "hooks_common"
version = "0.1.0"
authors = ["Leonard Dahlmann <leo.dahlmann@gmail.com>"]

[dependencies]
specs = "0.10.0"
shred = "0.5.0"
specs-derive = "0.1.0"
enet-sys = "0.1.4"
wrapped2d = "0.3.4"
serde = { version = "1.0", features = ["serde_derive"] }
nalgebra = { version = "0.13.1", features = ["serde-serialize"] }
