[package]
name = "hooks_common"
version = "0.1.0"
authors = ["leod <subtle.frustration@proton.me>"]

[dependencies]
specs = "0.10.0"
specs-derive = "0.1.0"
enet-sys = "0.1.4"
serde = { version = "1.0", features = ["serde_derive"] }
cgmath = { version = "0.15.0", features = ["serde"] }
