[package]
name = "hooks_common"
version = "0.1.0"
authors = ["Leonard Dahlmann <leo.dahlmann@gmail.com>"]

[dependencies]
serde = { version = "1.0", features = ["serde_derive"] }
bincode = "*"
bit_manager = "*"
bit_manager_derive = "*"
shred = "0.5.0"
specs = "0.10.0"
specs-derive = "0.1.0"
nalgebra = { version = "*", features = ["serde-serialize"] }
ncollide = { git = "https://github.com/sebcrozet/ncollide.git", branch = "send_sync" }
libc = "*"
enet-sys = "0.1.4"
mopa = "*"
